### ISSUE TITLE
Import tar file not working and no any log

### ISSUE THREAD

**Issue by AI-Robot-Morris** [FalconNL93/WslToolbox#13]
Hi,

Ver 0.6.23
Win 11 22H2 22621.2283

Import tar file not working and no any log

**Comment by AI-Robot-Morris** [comment]
issue i found my VM is disable, after enable the VM feature , it works fine. thx

**Comment by FalconNL93** [comment]
> issue i found my VM is disable, after enable the VM feature , it works fine. thx

Thanks. I will add a message when the vm feature in windows is disabled.
