### ISSUE TITLE
Don't ask for notification permissions every time the application is invoked.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [FalconNL93/WslToolbox#17]
> ![image](https://github.com/FalconNL93/WslToolbox/assets/42837531/d136fb64-5edb-4bdb-8d2b-f14ae2adbd66)

I'm using https://github.com/FalconNL93/WslToolbox/releases/download/0.7.28.0/WslToolbox.UI_0.7.28.0_x64.msix on Windows 11 build 22631.3737.

**Comment by FalconNL93** [comment]
Thanks, i will look into it :)

**Comment by FalconNL93** [comment]
I cant reproduce the issue. Do you launch the app every time by using the msix file or the created shortcut/start menu?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/FalconNL93/WslToolbox/issues/17#issuecomment-2198122092

@FalconNL93, if I were invoking the MSIX, surely I would be reinstalling it each time? Indeed, one would expect it to occur then. No, I'm using the `.lnk` file in `../Start Menu/`.

**Comment by FalconNL93** [comment]
Thanks, i found the culprit :) Will try to fix it

**Comment by FalconNL93** [comment]
I've released a new version which should solve this issue :)

https://github.com/FalconNL93/WslToolbox/releases/tag/0.7.31.0
