### ISSUE TITLE
Microsoft Store and winget listings are years out-of-date

### ISSUE THREAD

**Issue by stamminator** [FalconNL93/WslToolbox#18]
The [Microsoft Store listing for this app](https://www.microsoft.com/store/productId/9NDGGX7M2H0V?ocid=pdpshare) contains version 0.6.22, which was published in February 2023. The winget listing is even older, going back to January 2022.

```
> winget search "WSL toolbox"
Name             Id                    Version Source
-------------------------------------------------------
WSL Toolbox Beta 9NDGGX7M2H0V          Unknown msstore
WSL Toolbox      FalconNL93.WSLToolbox 0.5.13  winget
```

There have been several new versions published since these ones. Is there a reason these are falling so far behind? I'd love to try out a recent version, but because all of the installers hosted here in the GitHub releases have unverified certificates 🙁, I cannot install them on a policy-managed machine.

P.S. Because msstore is hot garbage that doesn't display version numbers, would you consider including it prominently in either the description or whatever text feeds the "what's new in this version" section?

**Comment by FalconNL93** [comment]
Hi,

There is no reason that winget & store is falling behind. I forgot to update them to be honest, I will try to update these packages asap :)

**Comment by FalconNL93** [comment]
> The [Microsoft Store listing for this app](https://www.microsoft.com/store/productId/9NDGGX7M2H0V?ocid=pdpshare) contains version 0.6.22, which was published in February 2023. The winget listing is even older, going back to January 2022.
> 
> 
> 
> ```
> 
> > winget search "WSL toolbox"
> 
> Name             Id                    Version Source
> 
> -------------------------------------------------------
> 
> WSL Toolbox Beta 9NDGGX7M2H0V          Unknown msstore
> 
> WSL Toolbox      FalconNL93.WSLToolbox 0.5.13  winget
> 
> ```
> 
> 
> 
> There have been several new versions published since these ones. Is there a reason these are falling so far behind? I'd love to try out a recent version, but because all of the installers hosted here in the GitHub releases have unverified certificates 🙁, I cannot install them on a policy-managed machine.
> 
> 
> 
> P.S. Because msstore is hot garbage that doesn't display version numbers, would you consider including it prominently in either the description or whatever text feeds the "what's new in this version" section?

Winget should be updated now. 

I added winget to the pipeline so it should automatically push new versions to winget.
