### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by DiamondUser** [FalconNL93/WslToolbox#6]
My operating system is Windows 11 21H2(version 22000.163)
and i want to install it to manage the wsl
it just let me to install .NET and though i have installed it and restart my computer,it still doesn't work.
![Screenshot_2022-05-11_13-09-35](https://user-images.githubusercontent.com/64264689/167773660-5bfe6e26-a54f-49da-a107-17c94ab6e07f.png)

**Comment by FalconNL93** [comment]
I will try to reproduce the error message. Should work with .net 5, which is installed on your system.

I will let you know!

**Comment by DiamondUser** [comment]
Oh thanks it works with .NET 5 installed!
