### ISSUE TITLE
Export suffix should be .tar not .tar.gz

### ISSUE THREAD

**Issue by vbrozik** [FalconNL93/WslToolbox#8]
When I create an export of a WSL2 distribution, WSL Toolbox adds `.tar.gz` suffix but the created file is a simple tar archive (not gzipped). The file should have `.tar` suffix.

**Comment by FalconNL93** [comment]
Thanks for reporting :), i will change it to tar.

**Comment by FalconNL93** [comment]
Fixed in nightly branch
